name: "Yarn Audit Fix"
description: "Fixes audited results by yarn"
author: "LoiLo"
inputs:
  github-repository:
    description: ":owner/:repo style github repository. Required by --create-deployment. Use github.repository."
    required: true
  github-token:
    description: "Github Token to create deployment on the repository. Required by --create-deployment. Use secrets.GITHUB_TOKEN."
    required: true
  git-user:
    description: "Git user name for commit changes"
    default: "Github Actions"
    required: false
  git-email:
    description: "Git user email for commit changes"
    default: "no-reply-actions@github.com"
    required: false
runs:
  using: "node12"
  main: "lib/index.js"
